### ISSUE TITLE
Better way to handle server errors

### ISSUE THREAD

**Issue by arvicco** [bitfinexcom/bitfinex-api-rb#13]
When REST request to server ends in error, the only info I get in my application using the library is something like this:
faraday-0.9.2/lib/faraday/response/raise_error.rb:13:in `on_complete': the server responded with status 400 (Faraday::ClientError)

In your program, you can rescue for this exception, but it doesn't give you any clue about what exactly went wrong. You need to enable debug mode on a client, and only then you can see in a console something like:
DEBUG -- response: {"message"=>"Invalid order: maximum size for BTCUSD is 2000.0 units"}

For the program using this lib, analyzing server response messages is often part of business logics. Eyeballing debug console to find what the error message was won't do it. There should be a better way of informing the program using this lib what kind of error message the server returned. This goes both for REST requests and WS error events. 

I don't currently have suggestions how to do it exactly, just food for thought.

**Comment by arvicco** [comment]
As per my pr, for failed REST requests returning code 400 now produce Bitfinex::Server exception with a meaningful message:
bitfinex-api-rb/lib/bitfinex/errors.rb:14:in `on_complete': Invalid offer: maximum lending period is 30 days (Bitfinex::ServerError)

Processing for all other errors is delegated to Faraday::Response::Middleware as before, so minimal impact.

**Comment by erubboli-bfx** [comment]
I've added some specs here: #17.
PR also add errors up to 500 to raise `Bitfinex::ServerError` but I'm not sure it makes sense though, maybe we should be more specific, especially with 403 and 500. What do you think? @prdn ?

**Comment by erubboli-bfx** [comment]
see #18

**Comment by erubboli-bfx** [comment]
@prdn  I think this can be closed
