### ISSUE TITLE
Any examples out there for how to use the Websocket side of this gem?

### ISSUE THREAD

**Issue by NullVoxPopuli** [bitfinexcom/bitfinex-api-rb#25]
I can figure it out, but I'm just looking for some quickstart-style examples -- just to save some time :-)

Thanks!

**Comment by erubboli-bfx** [comment]
I've added an example here:
https://github.com/bitfinexcom/bitfinex-api-rb/blob/b1ce138e85dadcd92bf81819053318515fca0080/examples/ws_client.rb

I'll create a PR soon

**Comment by f3rno** [comment]
I've added several examples in the `examples/` folder
