### ISSUE TITLE
LoadError: cannot load such file -- bitfinex-api-rb

### ISSUE THREAD

**Issue by Bitim** [bitfinexcom/bitfinex-api-rb#35]
Hi,

I installed bitfinex-api-rb with bundle successfully, after adding it to Gemsfile. Now I'm trying to load the the bitfinex-api-rb into my application in an initializer but get error when trying to start application:
> LoadError: cannot load such file -- bitfinex-api-rb

This is the initializer i'm using:
```
require 'bitfinex-api-rb'

Bitfinex::Client.configure do |config|
  config.key = GLOBAL[:bitfinex_key]
  config.secret = GLOBAL[:bitfinex_secret]
  config.websocket_api_endpoint = "wss://api.bitfinex.com/ws"
end
```

Any suggestion why?

Thanks.

**Comment by BeastOfBodmin** [comment]
You need to use

`require 'bitfinex'`

which is not clear.

**Comment by Bitim** [comment]
Yes, I already figured it out. Thanks anyway.
