### ISSUE TITLE
API v2 support

### ISSUE THREAD

**Issue by casper** [bitfinexcom/bitfinex-api-rb#38]
Is there support planned for the v2 API for this gem at some point? Or does there exist a v2 Ruby implementation somewhere already?

**Comment by ilyacherevkov** [comment]
It's fairly easy to adapt current gem to V2, just need little debugging for new methods

**Comment by d16sekine** [comment]
Can "bitfinex-api-rb" use the method "trades" in trading.rb ?
I executed client.trades("tBTCUSD"), but errors occured.

client.candles("tBTCUSD") was able to be executed without error.

**Comment by f3rno** [comment]
A class that implements v2 of the websocket API has been added on `master`
