### ISSUE TITLE
Invalid Auth Key Error

### ISSUE THREAD

**Issue by brettcomardelle** [bitfinexcom/bitfinex-api-rb#41]
I am using a correct api key and api secret, but it just isn't working. I keep getting the InvalidAuthKeyError message. I am using Ruby 2.4.

**Comment by mattdperkins** [comment]
I was having an auth error as well using the basic info from the readme.  
```require 'bitfinex-api-rb'  

require_relative 'config'  

client = Bitfinex::Client.new  

client.account_info  

```

```
irb(main):022:0> client.account_info  
Bitfinex::InvalidAuthKeyError: Bitfinex::InvalidAuthKeyError  
	from /usr/local/share/gems/gems/bitfinex-rb-0.0.11/lib/bitfinex/authenticated_rest.rb:6:in   `authenticated_post'  
	from /usr/local/share/gems/gems/bitfinex-rb-0.0.11/lib/bitfinex/account_info.rb:11:in `account_info'  
	from (irb):22  
	from /usr/bin/irb:11:in `<main>' 
```


Solved it by changing the secret and key setup slightly:  

```
Bitfinex::Client.configure do |conf|  
  conf.secret = "xxxxxxxxx"  
  conf.api_key = "xxxxxxxxx"  
end  
` ``

**Comment by MonsieurLanza** [comment]
ENV[...] is an env variable. You should not keep your secrets in the code, instead keep it in an .env file.

**Comment by ilyacherevkov** [comment]
I'm having the same issue with WS v2 occasionally

**Comment by f3rno** [comment]
I'm closing this as it is outdated, the repo has been (mostly) completely rewritten.
