### ISSUE TITLE
Unable to place order via API v2 Websockets occasionally

### ISSUE THREAD

**Issue by ilyacherevkov** [bitfinexcom/bitfinex-api-rb#43]
![screenshot 2017-08-14 00 14 59](https://user-images.githubusercontent.com/822364/29253724-2f0a3404-808e-11e7-90c2-b37503d181c3.jpg)

As it's seen on the screenshot, I'm placing 2 consequent orders via API v2 websockets.

First step: Buy IOT for BTC
Second step: Sell IOT for ETH
Third step: Sell ETH for BTC (not on the screen since 2nd step failed)

After the first order (IOT buy) goes through, I request IOT wallet update (calc function) to get actual amount available. I receive response:
[0, "wu", ["exchange", "IOT", 60.9, 0, 60.9]]
which tells that 60.9 IOT is available (not null)

I then send order 2 (Sell IOT), but it returns error 
`"Invalid order: not enough exchange balance for -60.9 IOTETH at 0.00269". `

Same order works via UI and REST. If I resend this order again, I immediately get disconnected and reconnected again. I can't figure whats wrong with my order and why im getting reconnected

**Comment by ilyacherevkov** [comment]
I've figured that when I resend order I supply nil arguments. However, I needed to resend order 24 times till it finally got accepted. It's not expected behaviour since wallet updated returns not nil value

`[0, "wu", ["exchange", "IOT", 60.9, 0, 60.9]]`

**Comment by ilyacherevkov** [comment]
Issue still persists, I even re-sent order 100 times once

**Comment by samuraraujo** [comment]
@ilyacherevkov did you manage to fix your issue. I think they do not maintain this api anymore.

**Comment by ilyacherevkov** [comment]
Im just spamming orders till they are accepted

**Comment by samuraraujo** [comment]
OK. And how long does it take to be accepted  ?

**Comment by ilyacherevkov** [comment]
Up to 100 tries
Im executing orders one by one, and backend is just slow to update avaialble balance, and doesn't allow to place order right away
