### ISSUE TITLE
Encryption not available on this event-machine

### ISSUE THREAD

**Issue by Vicckkky** [bitfinexcom/bitfinex-api-rb#48]
Hi

When I try to run the ticker.rb example, Ruby returns the following error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  Encryption not available on this event-machine

I compiled EventMachine with SSL but still get this error, any clue?

Thanks

**Comment by erubboli-bfx** [comment]
weird, is it related to https://github.com/eventmachine/eventmachine/issues/716 ?

**Comment by Vicckkky** [comment]
Found the solution here : https://github.com/eventmachine/eventmachine/issues/689

For some reason OpenSSL 1.1.0f, does not contain `ssleay' and 'libeay' thus doesn't compile properly EventMachine.
I went with OpenSSL 1.0.2L (previous version) & now it works properly !
