### ISSUE TITLE
"market" order with sufficient funds error

### ISSUE THREAD

**Issue by 18AdrianoH** [bitfinexcom/bitfinex-api-rb#50]
for an account with no margin capabilities, it refuses to put market orders because it wants to make a margin account
how do I order on market price w/out margin (I used the sample code on the bitfinex api site)

**Comment by erubboli-bfx** [comment]
You should use the type `exchange market` or `exchange limit` ecc. to operate without margin. 
See the `type` field documentation: https://bitfinex.readme.io/v1/reference#rest-auth-new-order

**Comment by 18AdrianoH** [comment]
I used the code from the example with exchange type market

Here is my code
`puts "Testing..."

require_relative './bitfinex_ruby_api/lib/bitfinex-api-rb.rb'

Bitfinex::Client.configure do |conf|
  conf.secret = thesecret
  conf.api_key = thekey
end

client = Bitfinex::Client.new
ticker = client.ticker
lastprice = ticker["last_price"]
puts client.new_order("BTCUSD", 0.01, "market", "buy", 1) #last param must be >1 or error is thrown
`
It gives me "This pair cannot be traded on margin. (Bitfinex::BadRequestError)"

**Comment by 18AdrianoH** [comment]
works ty
