### ISSUE TITLE
Support multiple secret and api_key

### ISSUE THREAD

**Issue by tomoyuki28jp** [bitfinexcom/bitfinex-api-rb#55]
I think it's better if we can create a new client with specified secret and api_key like following:

```
Bitfinex::Client.new(secret, api_key)
```

**Comment by soundasleep** [comment]
+1, otherwise sharing configuration between instances may put a user at risk of leaking credentials.

**Comment by f3rno** [comment]
This has basically been implemented on `master` as part of the rewrite
