### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by arvicco** [bitfinexcom/bitfinex-api-rb#6]
I see there is 'bitfinex/websocket.rb', but neither Faye nor Eventmachine are even in the gemspec. Is it just a stub atm?

**Comment by prdn** [comment]
We are working on the websocket feed, should be ready soon.

**Comment by arvicco** [comment]
Great! I messed around with it a bit and got public channels working with code like:
```ruby
bws = Bitfinex::Websocket::EMClient.new
bws.on ('open') { |_| bws.send( event: 'subscribe', channel: 'trades', pair: 'BTCUSD') }
bws.on ('message') { | json |  pp JSON.parse(json) }
```
I'm still not sure how to handle auth though, in order to receive account-specific channels. Maybe you happen have a Ruby snippet handy that you could share? I'm a bit obtuse with Javascript.

**Comment by prdn** [comment]
@arvicco have a look here: https://github.com/bitfinexcom/bitfinex-api-rb/pull/7

**Comment by arvicco** [comment]
Thanks! I tried to use new WebsocketConnection model to do ws auth, but no luck so far: 'websocket_connection.rb:27:in `ws_auth': undefined method `sign' for main:Object (NoMethodError)'

**Comment by erubboli-bfx** [comment]
Hi @arvicco, you should use the `listen_account` method passing a block, this is a full working example :

```ruby
require 'bitfinex'

Bitfinex::Client.configure do |conf|
    conf.api_key = ENV["BFX_KEY"]
    conf.secret = ENV["BFX_SECRET"]
end

client = Bitfinex::Client.new

client.listen_account do |c|
  puts "account: #{c.inspect}"
end

client.listen_ticker do |t|
  puts "tick: #{t.inspect}"
end

client.listen_book do |b|
  puts "book: #{b.inspect}"
end

client.listen_trades do |b|
  puts "trades: #{b.inspect}"
end

client.listen!
```

**Comment by arvicco** [comment]
Ah, sorry - it works now, I wasn't using the module API correctly - you need to call it's methods on Bitfinex::Client.

**Comment by arvicco** [comment]
Great job, guys! It does all I need atm.

**Comment by ilyacherevkov** [comment]
How do I send custom command (eg. place order) after I did `listen!`? Currently nothing happens.

**Comment by ilyacherevkov** [comment]
Do I understand correctly that this webosocket API is for live feed only? And it's not suited to place/cancel orders etc?
