### ISSUE TITLE
api_v2.rb example bug

### ISSUE THREAD

**Issue by cohensteiner** [bitfinexcom/bitfinex-api-rb#68]
When trying to run api_v2.rb, I get the following error:

from /Users//.gem/ruby/2.3.0/gems/bitfinex-rb-0.1.0/lib/bitfinex/errors.rb:29:in `[]': no implicit conversion of String into Integer (TypeError)

the problem happens at the line

p client.performance

Any idea how to fix this?

**Comment by f3rno** [comment]
I'm closing this as it is outdated, the repo has been (mostly) completely rewritten.
