### ISSUE TITLE
Facing issue with uninitialized constant Bitfinex::Client (NameError).

### ISSUE THREAD

**Issue by ramror3** [bitfinexcom/bitfinex-api-rb#78]
Hi,
I'm working on the Bitifinex API integration to my application. I have created the file in the config folder. When I'm running the server is getting uninitialized constant Bitfinex:: Client (NameError). Could you please help me with this issue. Please refer the below screenshot.
![bitfinex](https://user-images.githubusercontent.com/28476360/48689727-c801b180-ebf1-11e8-9f27-7c5134c7937b.png)

**Comment by ilyacherevkov** [comment]
You are using old version of the library. Initialisation params now are passed through params hash instead of block.

**Comment by f3rno** [comment]
Exactly, please have a look at the new readme. Thanks for your answer @ilyacherevkov

**Comment by ramror3** [comment]
Thanks for giving replay both of you @ilyacherevkov and @f3rno. I have fixed the issue.
