### ISSUE TITLE
Bitfinex::BadRequestError: Nonce is too small

### ISSUE THREAD

**Issue by larry82** [bitfinexcom/bitfinex-api-rb#85]
#### Issue type
- [x] bug

 #### Brief description

I didn't update any code but since 6/24 the restful API doesn't work.
Here are the code and error messages:

```
client = Bitfinex::RESTv1.new({
      :api_key => Rails.application.credentials.bitfinex[:key],
      :api_secret => Rails.application.credentials.bitfinex[:secret],
    })

fund_records = client.credits

```
result:

`Bitfinex::BadRequestError: Nonce is too small.`

**Comment by face** [comment]
Hi @larry82, 

I am unable to reproduce your issue.   Are you only using your API keys with this gem?   Some libraries might increment the Nonce differently, causing the `Nonce is too small` error.     

If you are using the API keys any where else, please try with new keys.   If you are only using them with this bitfinex gem, we will have to investigate further.

**Comment by larry82** [comment]
@face 
Thanks, I changed the key and everything works well again!

**Comment by face** [comment]
Great.   Thanks!
