### ISSUE TITLE
FundingTicker not working

### ISSUE THREAD

**Issue by larry82** [bitfinexcom/bitfinex-api-rb#86]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

 #### Brief description
I'm using WSv2 and the 'ticker' emit return empty object:
#<Bitfinex::Models::FundingTicker:0x00007fe75c6a2cc8 @fields={}, @boolFields=[]>

**Comment by face** [comment]
Hi @larry82,

Are you using the pub-api URL?   The following works for me:
```
require 'rubygems'
require 'bitfinex'

client = Bitfinex::WSv2.new({
  url:  'wss://api-pub.bitfinex.com/ws/2',
  transform: true
})

client.on(:ticker) do |symbol, msg|
  p "recv ticker message for symbol #{symbol}"
  p msg.serialize.join('|')

end

client.on(:open) do
  client.subscribe_ticker('fUSD')
end

client.open!
```

If you are still having issues, please share a code snippet that reproduces the issue.

Thanks

**Comment by larry82** [comment]
`I, [2019-07-07T20:26:54.711699 #37837]  INFO -- ws2: recv [179343,[0.0007134986301369863,0.000645,30,5003639.261537059,0.00063735,2,196897.94456750999,-0.0000024,-0.0034,0.000699,130755027.60711361,0.00071253,0.00000191,null,null,184654802.74329743]]
"recv ticker message for symbol fUSD"
"|||||||||||||"`

This is what I got after using your code

I'm using rails and this is my gem file

`source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'john_hancock'

gem 'bitfinex-rb', :require => "bitfinex"

gem "chartkick"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.0.rc1'
# Use postgresql as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 3.12'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry-rails'
  gem 'annotate'
  gem 'brakeman'
  gem 'bundler-audit'
  gem 'letter_opener_web', '~> 1.3', '>= 1.3.4'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Jumpstart dependencies
gem 'jumpstart', path: 'lib/jumpstart'

gem 'administrate', github: 'excid3/administrate', branch: 'jumpstart' #'~> 0.10.0'
gem 'attr_encrypted', '~> 3.1'
gem 'devise', '~> 4.6.0'
gem 'devise_invitable', '~> 2.0'
gem 'devise_masquerade', '~> 0.6.4'
gem 'image_processing', '~> 1.2'
gem 'inline_svg', '~> 1.3', '>= 1.3.1'
gem 'local_time', '~> 2.1'
gem 'name_of_person', '~> 1.0'
gem 'pagy', '~> 3.0'
gem 'pay', '~> 1.0.0.beta5'
gem 'receipts', '~> 0.2.2'
gem 'turbolinks_render', '~> 0.9.12'

# We always want the latest versions of these gems, so no version numbers
gem 'omniauth'
gem 'strong_migrations'
gem 'whenever', require: false

# Jumpstart manages a few gems for us, so install them from the extra Gemfile
if File.exists?("config/jumpstart/Gemfile")
  eval_gemfile "config/jumpstart/Gemfile"
end
`

**Comment by larry82** [comment]
I set the "transform" option to false and then the msg can be shown normally 

```
client = Bitfinex::WSv2.new({
      url:  'wss://api-pub.bitfinex.com/ws/2',
      transform: false
    })

    client.on(:ticker) do |symbol, msg|
      p "recv ticker message for symbol #{symbol}"
      p msg
    end

    client.on(:open) do
      client.subscribe_ticker('fUSD')
    end

    client.open!
```

```
"recv ticker message for symbol fUSD"
[0.000713345205479452, 0.000645, 30, 6087698.5942001995, 0.00062886, 2, 429636.50682435, -0.00010726, -0.1527, 0.00059522, 132211775.44697618, 0.00071253, 1.91e-06, nil, nil, 186125929.93047523]
```

**Comment by face** [comment]
Ok so it looks like it is working for you now.    If I'm mistaken I will re-open the issue.    Thank you.
