### ISSUE TITLE
Release Github versions to Rubygems 

### ISSUE THREAD

**Issue by unrooty** [bitfinexcom/bitfinex-api-rb#91]
Hello! I need functionality of the APIv2 but current 1.0.6 version is not synchronized with Rubygems and `bundle update` command has no effect. Can you please release Github version to Rubygems to give possibility to get latest changes?

**Comment by JacobPlaster** [comment]
Hi, we have just pushed the latest release to rubygems. Please try again

**Comment by unrooty** [comment]
@JacobPlaster Hello! Everything works fine! Thank you :smile:
